### ISSUE TITLE
Problem with compileing the program

### ISSUE THREAD

**Issue by NinoRazpotnik** [ReneRichterDE/ButtonMatrix#3]
Hello Rene,

Im currently working on Matrix keyboard project with MCP ic and im having problem.

When i try to compile i got error:

C:\Users\Admin\Documents\Arduino\Example04_i2c_ioexpansion\Example04_i2c_ioexpansion.ino:95:15: error: 'Button' in 'class RSys::ButtonMatrix' does not name a type
   95 | ButtonMatrix::Button buttons[ROWS][COLS] = {
      |               ^~~~~~
C:\Users\Admin\Documents\Arduino\Example04_i2c_ioexpansion\Example04_i2c_ioexpansion.ino:102:30: error: 'buttons' was not declared in this scope
  102 | ButtonMatrix matrix((Button*)buttons, rowPins, colPins, ROWS, COLS, ADFI2C(mcp));
      |                              ^~~~~~~

exit status 1

Compilation error: 'Button' in 'class RSys::ButtonMatrix' does not name a type

Can you plese help me with this error?

Greetings Nino

**Comment by ReneRichterDE** [comment]
I had a quick look into it and have been able to locate the problem:

The declaration in line 86 in the example is incorrect, if you replace this line:

`ButtonMatrix::Button buttons[ROWS][COLS] = {`

by this line:

`Button buttons[ROWS][COLS] = {`

it should do the trick. Please let me know if this sorted out your problem and I will update the repository accordingly.

Cheers
Rene

**Comment by ReneRichterDE** [comment]
Could you take the new example code from here?

https://github.com/ReneRichterDE/ButtonMatrix/blob/main/examples/Example04_i2c_ioexpansion/Example04_i2c_ioexpansion.ino

If the error still persists, can you put the whole error message in here again?

**Comment by ReneRichterDE** [comment]
Hi Nino,
I have released version 1.0.2 that fixes the bug with the example for  i2c connected devices as well as a compiler error regarding duplicate definitions. It might take a while for the new version to show up in the Arduino IDE library manager.
You might want to try that version and let me know if that solved your problems.

**Comment by NinoRazpotnik** [comment]
Hello Rene,

I managed to compile and upload program. 
Now im trying to fix another problem. Now it reads that all buttons are pressed, ei. . How can i invert logic of buttons?

Greetings Nino

**Comment by ReneRichterDE** [comment]
Hello Nino,

I have moved your case to a new issue as it is not related to the original case, which I am closing now since fixed with v1.0.2
I will follow up on the new topic [here](https://github.com/ReneRichterDE/ButtonMatrix/issues/4#issue-2520109552)
