### ISSUE TITLE
Question about MCP23017 PIN Designation

### ISSUE THREAD

**Issue by jdec84** [ReneRichterDE/ButtonMatrix#6]
My question is simply how do I specify which button will be assigned to which pin on MCP? How does the code know PORTA , PORTB and which pin on each for the matrix? It just isn't making obvious sense to me and it doesn't seem to be explained in the commenting. Thank you for creating this library and answering my question.

John

**Comment by ReneRichterDE** [comment]
Hi John,

this library is designed to handle larger amounts of buttons that are connected in a special way sharing ports among them,
If you want to connect 16 buttons to a MC in the ordinary way, it would require 16 inputs and 64 buttons would require 64 inputs.

With this special technique 16 button just require 8 IO pins while 64 buttons require 16 IO pins. You can see the difference, this technique saves a lot of IO pins.

If you want to read about the details on how it works, I recommend to check out this article here:

[How key matrices work](https://www.pcbheaven.com/wikipages/How_Key_Matrices_Works/)

Did it answer your question?

~Rene

**Comment by jdec84** [comment]
I completely understand how a button matrix works. I am just wondering
where in your code the specific pins of the mcp are referenced. I have an
button array of 25, and I will be using 2 mcp23017 to expander. But will
need to know which mcp pins will reach each column and row

Thanks you

**Comment by ReneRichterDE** [comment]
If you look at the sample code in **Example04_i2c_ioexpansion.ino**, you will find those lines where you define the pins for you matrix.

Here you define the number of pins for columns and rows:

```
const uint8_t COLS = 3; /** Number of button matrix columns */
const uint8_t ROWS = 3; /** Number of button matrix rows */
```

And here the pin numbers:

```
uint8_t colPins[COLS] = {4,5,6}; /** Button matrix column pins */
uint8_t rowPins[ROWS] = {0,1,2}; /** Button matrix row pins */
```
In this example the column pins are: 4, 5, and 6 and the row pins are 0, 1 and 2 on the MCP.

For 25 buttons you do not require two MCP23017 as each module supports 16 IO while you just need 10 IO for 25 buttons.
Multi-MCP support will be released in version 1.1.0 in about one or two weeks though.

**Comment by jdec84** [comment]
Thank you for your responses. So are the pins you're using  1-8 and the
21-28 would be the pin numbers referenced in your code? Or is it just 1-16
or 0-15 as referenced in the attached diagram?

Sorry i just like to research a lot before I jump into something.

**Comment by jdec84** [comment]
![mcp23017-pinout-library-pins](https://github.com/user-attachments/assets/ae74d7f4-760b-4f2c-9886-57f858cddb97)

**Comment by jdec84** [comment]
![mcp23017-pinout-library-pins](https://github.com/user-attachments/assets/34e43f11-47ed-4be4-9343-9f2d1d58db15)

**Comment by ReneRichterDE** [comment]
The pin number mapping for the MCP is:

Pin 0..7 -> GPA0 .. GPA7
Pin 8..15 -> GPB0 .. GPB7

**Comment by jdec84** [comment]
Thank you for clarifying this. Also thanks again for creating this life
saving library!

**Comment by ReneRichterDE** [comment]
You're welcome John ... I am glad the library is of good use for you!
